// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weather.Infrastructure.Persistence;

#nullable disable

namespace Weather.Infrastructure.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20251201181206_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Weather.Infrastructure.Persistence.Entities.CitySubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NextPollAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PollingIntervalMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityName");

                    b.HasIndex("IsActive", "NextPollAt");

                    b.ToTable("CitySubscriptions");
                });

            modelBuilder.Entity("Weather.Infrastructure.Persistence.Entities.WeatherMeasurementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitySubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CitySubscriptionId", "Timestamp");

                    b.ToTable("WeatherMeasurements");
                });

            modelBuilder.Entity("Weather.Infrastructure.Persistence.Entities.WeatherMeasurementEntity", b =>
                {
                    b.HasOne("Weather.Infrastructure.Persistence.Entities.CitySubscriptionEntity", "CitySubscription")
                        .WithMany("Measurements")
                        .HasForeignKey("CitySubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CitySubscription");
                });

            modelBuilder.Entity("Weather.Infrastructure.Persistence.Entities.CitySubscriptionEntity", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
